name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # 1. This job formats and saves styling fixes safely
  fix-style:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      # Fixes the HTTP 400 Error by stripping out standard authentication headers
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Fixes the Duplicate Header Error by telling homebrew not to overwrite settings
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          test-bot: false

      - name: Set up Git User Configuration
        uses: Homebrew/actions/git-user-config@main

      - name: Auto-fix Homebrew style issues
        run: |
          if [ -d "Casks" ]; then brew style --fix Casks/; fi
          if [ -d "Formula" ]; then brew style --fix Formula/; fi
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-fix Homebrew styling issues"
          fi

      - name: Push Auto-fixes Natively
        uses: Homebrew/actions/git-try-push@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

  # 2. This job executes your actual tests once the files are clean
  test-bot:
    needs: fix-style
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
